### ISSUE TITLE
Line 822 in dbInit.py does not compile

### ISSUE THREAD

**Issue by FredStein** [bmw2621/dnd5eGQL#1]
https://github.com/bmw2621/dnd5eGQL/blob/3e0fdfb1db3705e23b52ea82229f50dd5f25597c/dbInit.py#L822

Hi,
   I'm using python 3.6 & looking to use the sqlLite 3 db generated as a local back end. 

Very nice use of f strings but I cannot get l822 to compile.

Any thoughts? Anyone?

Corwin.

**Comment by bmw2621** [comment]
@FredStein

Interesting, fstrings was released in 3.6.

you could try replacing it with. 

` "; ".join(['{0}: walk - {1} climb - {2}'.format(form["form"], form["speed"]["walk"], form["speed"]["climb"] if "climb" in form["speed"].keys() else "")for form in monster["other_speeds"]]) if "other_speeds" in monster.keys() else None,`

but I would be surprised if that's the issue.

Can you copy the error into the issue?

BTW, thanks for finding one of the most embarrassing lines of code in this project... ;)

**Comment by bmw2621** [comment]
BTW, thanks for finding one of the most embarrassing lines of code in this project... ;)

**Comment by FredStein** [comment]
Sure.

**Comment by FredStein** [comment]
PyDev under Eclipse.

 

I take no credit.

 

There is more going on here. When I comment out the line PyDev picks up the next use of f as an error, and so on.

 

I’ll look at this with a different syntax checker.

**Comment by FredStein** [comment]
It's not you, it's me.

Or more accurately it's PyDev.

Runs fine under Idle & PyCharm.

PyDev throws: an error at Line 822, specifically tagging f.

The error message is "Expected:] \n Expected:]"

Commenting out 822 then throws an error at 842:

record = (monster["index"], f'{sense} - {monster["senses"][sense]}')

"Expected:) \n Expected:])"

Commenting out 842 then throws an error at line 980:

 f'{equipment["cost"]["quantity"]} {equipment["cost"]["unit"]}' if "cost" in equipment.keys() else None,

"Expected:) \n Expected:])"

etc ...


It appears PyDev does not correctly sort out scope while PyCharm / Idle do.

I'll log this with PyDev.

Issue closed for me. Using PyCharm now :-)
